version: '3'
services:
  streamlit:
    restart: always 
    build: .
    container_name: 'streamlit_py3'
    working_dir: '/root/src'
    tty: true 
    ports: 
     - "0.0.0.0:8501:8501"
    volumes:
     - ${SRC_PATH}:/root/src
